-- Esquema H2. Las FK preservan el historial: no hay borrados en cascada.
CREATE TABLE IF NOT EXISTS moneda (
    moneda_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    codigo VARCHAR(3) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    simbolo VARCHAR(5),
    CONSTRAINT uq_moneda UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS permiso (
    permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(250),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT uq_permiso UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS rol (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT uq_rol UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS tipo_cuenta (
    tipo_cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT uq_tipo_cuenta UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    nombre_completo VARCHAR(150) NOT NULL,
    correo VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    foto_url VARCHAR(500),
    programa_academico VARCHAR(150),
    moneda_id BIGINT NOT NULL REFERENCES moneda(moneda_id),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_registro DATE NOT NULL,
    fecha_actualizacion DATE,
    CONSTRAINT uq_usuario UNIQUE (correo)
);

CREATE TABLE IF NOT EXISTS cuenta (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    tipo_cuenta_id BIGINT NOT NULL REFERENCES tipo_cuenta(tipo_cuenta_id),
    nombre VARCHAR(100) NOT NULL,
    saldo_inicial NUMERIC(15,2) NOT NULL,
    saldo_actual NUMERIC(15,2) NOT NULL,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVA', 'ARCHIVADA')),
    fecha_creacion DATE NOT NULL,
    fecha_archivado DATE
);

CREATE TABLE IF NOT EXISTS categoria (
    categoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuario(usuario_id),
    nombre VARCHAR(100) NOT NULL,
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('INGRESO', 'GASTO')),
    descripcion VARCHAR(200),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS movimiento (
    movimiento_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    cuenta_id BIGINT NOT NULL REFERENCES cuenta(cuenta_id),
    categoria_id BIGINT NOT NULL REFERENCES categoria(categoria_id),
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('INGRESO', 'GASTO')),
    monto NUMERIC(15,2) NOT NULL,
    fecha_movimiento DATE NOT NULL,
    descripcion VARCHAR(500),
    soporte_url VARCHAR(500),
    fecha_creacion DATE NOT NULL,
    CHECK (monto > 0)
);

CREATE TABLE IF NOT EXISTS movimiento_recurrente (
    recurrente_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    cuenta_id BIGINT NOT NULL REFERENCES cuenta(cuenta_id),
    categoria_id BIGINT NOT NULL REFERENCES categoria(categoria_id),
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('INGRESO', 'GASTO')),
    monto NUMERIC(15,2) NOT NULL,
    periodicidad VARCHAR(15) NOT NULL CHECK (periodicidad IN ('SEMANAL', 'QUINCENAL', 'MENSUAL')),
    fecha_inicio DATE NOT NULL,
    fecha_corte DATE,
    proxima_ocurrencia DATE NOT NULL,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'SUSPENDIDO', 'INACTIVO')),
    descripcion VARCHAR(500),
    CHECK (monto > 0)
);

CREATE TABLE IF NOT EXISTS presupuesto (
    presupuesto_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    categoria_id BIGINT NOT NULL REFERENCES categoria(categoria_id),
    anio INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    monto_limite NUMERIC(15,2) NOT NULL,
    fecha_creacion DATE NOT NULL,
    CONSTRAINT uq_presupuesto UNIQUE (usuario_id,categoria_id,anio,mes),
    CHECK (mes BETWEEN 1 AND 12),
    CHECK (monto_limite > 0)
);

CREATE TABLE IF NOT EXISTS deuda (
    deuda_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    contraparte_usuario_id BIGINT REFERENCES usuario(usuario_id),
    contraparte_nombre VARCHAR(150),
    tipo VARCHAR(15) NOT NULL CHECK (tipo IN ('POR_PAGAR', 'POR_COBRAR')),
    monto_original NUMERIC(15,2) NOT NULL,
    fecha_origen DATE NOT NULL,
    fecha_limite DATE NOT NULL,
    descripcion VARCHAR(500),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('PENDIENTE', 'SALDADA')),
    saldo_pendiente NUMERIC(15,2) NOT NULL,
    CHECK (fecha_limite >= fecha_origen),
    CHECK (monto_original > 0 AND saldo_pendiente BETWEEN 0 AND monto_original),
    CHECK (contraparte_usuario_id IS NOT NULL OR COALESCE(LENGTH(TRIM(contraparte_nombre)), 0) > 0)
);

CREATE TABLE IF NOT EXISTS abono_deuda (
    abono_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    deuda_id BIGINT NOT NULL REFERENCES deuda(deuda_id),
    monto NUMERIC(15,2) NOT NULL,
    fecha_abono DATE NOT NULL,
    descripcion VARCHAR(300),
    CHECK (monto > 0)
);

CREATE TABLE IF NOT EXISTS plan_ahorro (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    propietario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    monto_objetivo NUMERIC(15,2) NOT NULL,
    fecha_objetivo DATE NOT NULL,
    tipo VARCHAR(15) NOT NULL CHECK (tipo IN ('INDIVIDUAL', 'COMPARTIDO')),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'CERRADO', 'ARCHIVADO')),
    fecha_creacion DATE NOT NULL,
    CHECK (monto_objetivo > 0)
);

CREATE TABLE IF NOT EXISTS invitacion_plan (
    invitacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES plan_ahorro(plan_id),
    usuario_invitado_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    usuario_invitador_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA')),
    fecha_invitacion DATE NOT NULL,
    fecha_respuesta DATE
);

CREATE TABLE IF NOT EXISTS aporte_plan (
    aporte_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES plan_ahorro(plan_id),
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    cuenta_id BIGINT NOT NULL REFERENCES cuenta(cuenta_id),
    monto NUMERIC(15,2) NOT NULL,
    fecha_aporte DATE NOT NULL,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO', 'RETIRADO')),
    fecha_creacion DATE NOT NULL,
    CHECK (monto > 0)
);

CREATE TABLE IF NOT EXISTS usuario_rol (
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    rol_id BIGINT NOT NULL REFERENCES rol(rol_id),
    PRIMARY KEY (usuario_id, rol_id),
    fecha_asignacion DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS rol_permiso (
    rol_id BIGINT NOT NULL REFERENCES rol(rol_id),
    permiso_id BIGINT NOT NULL REFERENCES permiso(permiso_id),
    PRIMARY KEY (rol_id, permiso_id),
    fecha_asignacion DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS participacion_plan (
    plan_id BIGINT NOT NULL REFERENCES plan_ahorro(plan_id),
    usuario_id BIGINT NOT NULL REFERENCES usuario(usuario_id),
    PRIMARY KEY (plan_id, usuario_id),
    meta_individual NUMERIC(15,2) CHECK (meta_individual > 0),
    fecha_aceptacion DATE,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO','RETIRADO'))
);
