spring.application.name=finanzas-personales
spring.profiles.default=demo
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.jackson.deserialization.fail-on-unknown-properties=true
server.port=${SERVER_PORT:8080}
server.error.include-message=never
